backend:
  name: github
  repo: edisim/decap-cms-now
  branch: master
  base_url: https://decap-cms-now.vercel.app
  auth_endpoint: api/auth

media_folder: /img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    folder: "settings"
    create: false
    slug: "settings"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Favicon", name: "favicon", widget: "image" }
      - { label: "Footer", name: "footer", widget: "string" }
      - {
          label: "Navigation",
          name: "navigation",
          widget: "list",
          fields:
            [
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" },
            ],
        }
  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Github", name: "github", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - {
          label: "Linkedin",
          name: "linkedin",
          widget: "string",
          required: false,
        }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: false,
        }
      - { label: "Role", name: "role", widget: "string", required: false }
# demo to show netlify's possibilities

